import React from 'react';

import type { NextPage } from 'next'
import { useEffect, useState } from 'react'

import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import Menu from './Menu'
import Rodape from './Rodape'

interface Props {
    title: string
}

const Home: NextPage <Props> = (props) => {
    const [load, setLoad] = useState<boolean>(true);

    useEffect(() => {
        setLoad(false);
    }, []);

    return (
        <>
            <div className={styles.preload}>
                <i></i>
            </div>
            <div className={styles.container}>
                <Head>
                    <title>{props.title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <header>
                    <Menu></Menu>
                </header>
                <div className={styles.tudo}>
                    <main className={styles.main}>
                        {props.children}
                    </main>

                    <footer className={styles.footer}>
                        <Rodape></Rodape>
                    </footer>
                </div>
            </div>
        </>
    )
}

export default Home